

export enum SubscriptionType {
  PREMIUM_JOB_SEEKER = 'PREMIUM_JOB_SEEKER',
  PREMIUM_EMPLOYER = 'PREMIUM_EMPLOYER',
}

export enum JobType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  INTERNSHIP = 'INTERNSHIP',
  FREELANCE = 'FREELANCE',
}

export enum JobStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  DRAFT = 'DRAFT',
}

export enum UserRole {
  JOB_SEEKER = 'JOB_SEEKER',
  EMPLOYER = 'EMPLOYER',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  PREMIUM_JOB_SEEKER = 'PREMIUM_JOB_SEEKER',
  PREMIUM_EMPLOYER = 'PREMIUM_EMPLOYER',
}